undef_action: error
out: /mnt/production/compute-daemon/utils/my_analysis.sig_queryl1k_tool.627c44bf909297001232569a/gsea/TAG
runtests: false
rundemo: false
rpt: []
create_subdir: false
verbose: true
encode_url: false
config: []
up: /cmap/data/vdb/sigtool_assets/gseapreranked/cmap_sig_sets_n12100.gmt
score: '[423422x1 ds] /mnt/production/compute-daemon/utils/my_analysis.sig_queryl1k_tool.627c44bf909297001232569a/arfs/TAG/query_result.gct'
rank: '[423422x1 ds] /mnt/production/compute-daemon/utils/my_analysis.sig_queryl1k_tool.627c44bf909297001232569a/arfs/TAG/query_result.gct'
sig_meta: []
metric: wtcs
es_tail: up
num_perm: 500.0
query_meta: /cmap/data/vdb/sigtool_assets/gseapreranked/cmap_sig_sets_info.txt
save_minimal: true
save_digests: true
max_col: 25000.0
