undef_action: warn
out: /mnt/production/compute-daemon/utils/my_analysis.sig_curie_tool.627c31f29092970012325696
runtests: false
rundemo: false
rpt: Cell lines with high gene expression of PDGFRA
create_subdir: false
verbose: true
encode_url: false
config: http://data.clue.io/api/bgarana@usc.edu/results/May_11_2022/my_analysis.sig_curie_tool.627c31f29092970012325696/config.yaml
score: /cmap/data/build/curie-assets/datasets/PREP2/PREP014-48_SECONDARY_REPROCESS_SQRTAUC_n1258x489.gctx
rank: '[489x1258 ds] /cmap/data/build/curie-assets/datasets/PREP2/PREP014-48_SECONDARY_REPROCESS_RANK.SQRTAUC_n1258x489.gctx'
up: http://data.clue.io/api/bgarana%40usc.edu/results/May_11_2022/my_analysis.sig_curie_tool.627c31f29092970012325696/up.gmt
down: http://data.clue.io/api/bgarana%40usc.edu/results/May_11_2022/my_analysis.sig_curie_tool.627c31f29092970012325696/down.gmt
min_set_size: 3.0
platform: pr500_cs5
feature_space: cell_iname
metric: wtcs
es_tail: up
sig_meta: /cmap/data/build/curie-assets/datasets/PREP2/PREP014-48_SECONDARY_REPROCESS_sig_info.txt
query_meta: []
skip_key_as_text: false
dataset: custom
dataset_source: /cmap/data/vdb/sigtool_assets/curie/sig_curie_tool_datasets.txt
use_gctx: false
